version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - git submodule init
      - git submodule update --recursive
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/eureka-0.0.1-SNAPSHOT.jar